### PR TITLE
IOD202-Navigation

### PR DESCRIPTION
**Pull request by aideninbcgov**
# Description

This PR includes the following proposed change(s):

- {List all the changes, if possible add the jira ticket #}

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aideninbcgov** [comment]
nav styling jsfied

**Review by akroon3r — DISMISSED** [review]
looking good on first pass

**Comment by akroon3r** [comment]
@aideninbcgov one merge conflict to resolve

**Comment by aideninbcgov** [comment]
@akroon3r it's resolved now.

**Comment by akroon3r** [comment]
@aideninbcgov please review my message on teams first, and ensure that docker is building the image locally first before we try to push this to dev.

**Comment by aideninbcgov** [comment]
@akroon3r rebase done. docker-compose build tested.

**Review by SDToews — APPROVED** [review]

**Pull request merged**
