### PR TITLE
IOD-109 Dockerize + docker-compose for Frontend Application

### PR DESCRIPTION
**Pull request by akroon3r**
# Description

This PR includes the following proposed change(s):

IOD-109

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [x] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by akroon3r** [comment]
!IMPORTANT!

Please check out my working branch and run the docker-compose command to ensure this works!

Let me know if you have any feedback in comments below.

**Review by aideninbcgov — COMMENTED** [review]
I was hoping to test it before approving it, but it seems I can only pull once merge process is done which happens after approving the pull request. any thoughts?

**Comment by akroon3r** [comment]
you should checkout main and pull. Double check that you a see a reference to the branch named "dockerize-app" is created.  Then you should be able to git checkout dockerize-app to get my working branch on your local.

**Comment by aideninbcgov** [comment]
gotcha. testing now.

**Comment by akroon3r** [comment]
message me on teams if you have any issues :)

**Comment by SDToews** [comment]
There seems to be a lot of file changes not related to dockerization here, can we discuss?

**Comment by akroon3r** [comment]
@SDToews it looks like Aiden pushed changes into my working branch when he did local testing.

**Comment by akroon3r** [comment]
@SDToews it looks like Aiden pushed changes into my working branch when he did local testing.

**Comment by akroon3r** [comment]
@aideninbcgov @SDToews I've rolled the branch back to [4c0441e](https://github.com/bcgov/citz-imb-slam-app/pull/37/commits/4c0441e061a4ee308cf5ba0e4f00d53e24c0b6d0)

**Review by SDToews — APPROVED** [review]

**Pull request merged**
